version: '3.7'

services:
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: musicwebapp-backend-image
    container_name: musicwebapp-backend-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: musicwebapp-frontend-image
    container_name: musicwebapp-frontend-container
    command: npm start
    stdin_open: true
    volumes:
      - .client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local